% FUNCTION NAME:
%   evalcfrac
%
% DESCRIPTION:
%   Backward evaluation of a continued fraction
%       aa1 + (x-zz1)/aa2+... 
%
%
% INPUT:
%   aa - (vector double) inverse differences
%   zz - (vector double) associated locations used
%   x  - (vector double) location where to evaluate
%
%
% OUTPUT:
%   r - evaluation of continued fraction at x
%
%
% ASSUMPTIONS AND LIMITATIONS:
%   aa and zz are generated by cfrac_interpolate
%
%
% REFERENCE:
%   Numerical Continued Fraction Interpolation
%   Oliver Salazar Celis
%   https://doi.org/10.48550/arXiv.2109.10529
%
%
% See also cfrac_interpolate, prz_cfrac
